name: Release workflow

on:
  push:
    branches:
      - 'try_deployment'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'temurin'
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: MAVEN_USERNAME  # env variable for username in deploy
          server-password: MAVEN_CENTRAL_TOKEN  # env variable for token in deploy
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: GPG_PASSPHRASE # env variable for GPG private key passphrase

      - name: check that the settings file exists
        run: cat $HOME/.m2/settings.xml

      - name: Encrypt master password
        run: |
          MASTER_PASSWORD=$(mvn --encrypt-master-password "Sw0rdf1sh1$Th3P@$$w0rd")
          echo "<settingsSecurity>" > $HOME/.m2/settings-security.xml
          echo "  <master>${MASTER_PASSWORD}</master>" >> $HOME/.m2/settings-security.xml
          echo "</settingsSecurity>" >> $HOME/.m2/settings-security.xml

      - name: Build and deploy with maven
        run: mvn deploy